<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.5" xml:lang="en-US">
  <compounddef id="class_catch_1_1_generator_exception" kind="class" language="C++" prot="public">
    <compoundname>Catch::GeneratorException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">std::exception</basecompoundref>
    <includes refid="catch_8hpp" local="no">catch.hpp</includes>
      <sectiondef kind="private-attrib">
      <memberdef kind="variable" id="class_catch_1_1_generator_exception_1a493b6ec9e3be0e3852de73c87dba6e5e" prot="private" static="no" mutable="no">
        <type>const char *const</type>
        <definition>const char* const Catch::GeneratorException::m_msg</definition>
        <argsstring></argsstring>
        <name>m_msg</name>
        <qualifiedname>Catch::GeneratorException::m_msg</qualifiedname>
        <initializer>= &quot;&quot;</initializer>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="shadow-engine/shadow-file-format/test/catch2/catch.hpp" line="3920" column="22" bodyfile="shadow-engine/shadow-file-format/test/catch2/catch.hpp" bodystart="3920" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="class_catch_1_1_generator_exception_1a3cf9282d555ec32389665ce723bf36ea" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>Catch::GeneratorException::GeneratorException</definition>
        <argsstring>(const char *msg)</argsstring>
        <name>GeneratorException</name>
        <qualifiedname>Catch::GeneratorException::GeneratorException</qualifiedname>
        <param>
          <type>const char *</type>
          <declname>msg</declname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="shadow-engine/shadow-file-format/test/catch2/catch.hpp" line="3923" column="5" bodyfile="shadow-engine/shadow-file-format/test/catch2/catch.hpp" bodystart="3923" bodyend="3925"/>
      </memberdef>
      <memberdef kind="function" id="class_catch_1_1_generator_exception_1ac40705ff5da208ce3a7d3023d0d3f4c6" prot="public" static="no" const="yes" explicit="no" inline="no" final="yes" noexcept="yes" virt="non-virtual">
        <type>const char *</type>
        <definition>const char * Catch::GeneratorException::what</definition>
        <argsstring>() const noexcept override final</argsstring>
        <name>what</name>
        <qualifiedname>Catch::GeneratorException::what</qualifiedname>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="shadow-engine/shadow-file-format/test/catch2/catch.hpp" line="3927" column="16"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>Catch::GeneratorException</label>
        <link refid="class_catch_1_1_generator_exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>std::exception</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>Catch::GeneratorException</label>
        <link refid="class_catch_1_1_generator_exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>std::exception</label>
      </node>
    </collaborationgraph>
    <location file="shadow-engine/shadow-file-format/test/catch2/catch.hpp" line="3919" column="1" bodyfile="shadow-engine/shadow-file-format/test/catch2/catch.hpp" bodystart="3919" bodyend="3928"/>
    <listofallmembers>
      <member refid="class_catch_1_1_generator_exception_1a3cf9282d555ec32389665ce723bf36ea" prot="public" virt="non-virtual"><scope>Catch::GeneratorException</scope><name>GeneratorException</name></member>
      <member refid="class_catch_1_1_generator_exception_1a493b6ec9e3be0e3852de73c87dba6e5e" prot="private" virt="non-virtual"><scope>Catch::GeneratorException</scope><name>m_msg</name></member>
      <member refid="class_catch_1_1_generator_exception_1ac40705ff5da208ce3a7d3023d0d3f4c6" prot="public" virt="non-virtual"><scope>Catch::GeneratorException</scope><name>what</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
